.TH constatus 1 "2017-09-10" "constatus" "User Commands"
.SH NAME
constatus \- Records a videofile when motion is detected via a camera.
.SH SYNOPSIS
\fBconstatus\fP [options]
.SH DESCRIPTION
\fBconstatus records a videofile when motion is detected via a camera.
Constatus supports locally attached camera's or network cameras via MJPEG/RTSP.
.SH OPTIONS
.PP
.IP "\fB\-c\fR \fR\fIconfig\fR"
Specify a path to the config file to use.
.IP "\fB\-f\fR"
Fork into the background
.IP "\fB\-p\fR \fR\fIpidfile\fR"
Specify a pidfile to write PID to.
.IP "\fB\-v\fR"
Enable verbose mode.
.IP "\fB\-V\fR"
Display version information.
.IP "\fB\-h\fR"
Display help message.
